### ISSUE TITLE
Vanished players kick everyone on chat

### ISSUE THREAD

**Issue by Entropy159** [DrexHD/Vanish#38]
When I vanish on my server and then say something in the chat, it kicks everyone else off and says "Received chat package with missing or invalid signature". I think this occurs because they receive a chat message from a nonexistent player, but idk.

**Comment by DrexHD** [comment]
That's why this mod provides the `disable-chat` config option to prevent vanished players from accidentally kicking everyone. If you want to send messages in chat regardless, you must send your message "non report-able" (eg. /tellraw or using other mods).
Chat validation / reporting relies on knowing all involved players, which is fundamentally incompatible with the concept of hiding a vanished player!
