### ISSUE TITLE
When doing /deop the affected player can still see the player in /vanish in the tab list (until they relog)

### ISSUE THREAD

**Issue by 42Eagler** [DrexHD/Vanish#45]
Player 1 has op.
Player 2 is in vanish and visible to player 1.

Player 1 does /deop.
Player 2 disappears in-game but is still visible in the tab list.
Player 1 leaves and joins the game.
Player 2 is now truly in vanish and everything works correctly.

**Comment by DrexHD** [comment]
The same problem occurs when players permission change (they get/lose `vanish.feature.view`), which is not properly detectable. I don't currently plan to support this as it would introduce a good amount of work and increase likely-hood of bugs. And this usually shouldn't be to much of a problem, because this usually rarely happens.
